apiVersion: network.azure.upbound.io/v1beta1
kind: NATGateway
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    idleTimeoutInMinutes: 10
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Standard
    zones:
    - "1"

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
