apiVersion: communication.azure.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: communication/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dataLocation: United States
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: communication/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
