apiVersion: network.azure.upbound.io/v1beta1
kind: DDoSProtectionPlan
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/ddosprotectionplan
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/ddosprotectionplan
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
