apiVersion: network.azure.upbound.io/v1beta1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/loadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    frontendIpConfiguration:
    - name: PublicIPAddress
      publicIpAddressIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.upbound.io/v1beta1
kind: PublicIP
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/loadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allocationMethod: Static
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/loadbalancer
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
