apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityRule
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    access: Allow
    destinationAddressPrefix: '*'
    destinationPortRange: '*'
    direction: Outbound
    networkSecurityGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    priority: 100
    protocol: Tcp
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sourceAddressPrefix: '*'
    sourcePortRange: '*'

---

apiVersion: network.azure.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/securityrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
