apiVersion: network.azure.upbound.io/v1beta1
kind: SubnetServiceEndpointStoragePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    definition:
    - description: definition1
      name: name1
      serviceResources:
      - ${azurerm_resource_group.example.id}
      - ${azurerm_storage_account.example.id}
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/subnetserviceendpointstoragepolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: GRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
