apiVersion: relay.azure.upbound.io/v1beta1
kind: HybridConnection
metadata:
  annotations:
    meta.upbound.io/example-id: relay/v1beta1/hybridconnection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: acctestrnhc-%d
    relayNamespaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    requiresClientAuthorization: false
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    userMetadata: testmetadata

---

apiVersion: relay.azure.upbound.io/v1beta1
kind: EventRelayNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: relay/v1beta1/hybridconnection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Standard
    tags:
      source: terraform

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: relay/v1beta1/hybridconnection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
