apiVersion: automation.azure.upbound.io/v1beta1
kind: HybridRunBookWorkerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1beta1/hybridrunbookworkergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    automationAccountName: example
    name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
