apiVersion: powerbidedicated.azure.upbound.io/v1beta1
kind: PowerBIEmbedded
metadata:
  annotations:
    meta.upbound.io/example-id: powerbidedicated/v1beta1/powerbiembedded
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administrators:
    - azsdktest@microsoft.com
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: A1

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: powerbidedicated/v1beta1/powerbiembedded
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
