apiVersion: dbformariadb.azure.upbound.io/v1beta1
kind: FirewallRule
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1beta1/firewallrule
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    endIpAddress: 40.112.8.12
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    startIpAddress: 40.112.8.12
