apiVersion: compute.azure.upbound.io/v1beta1
kind: DedicatedHost
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/dedicatedhost
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dedicatedHostGroupId: ${azurerm_dedicated_host_group.example.id}
    location: West Europe
    platformFaultDomain: 1
    skuName: DSv3-Type1

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/dedicatedhost
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
