apiVersion: compute.azure.upbound.io/v1beta1
kind: ProximityPlacementGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/proximityplacementgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      environment: Production

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/proximityplacementgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
